spring:
  profiles:
    active:
    - dev
    
----

server:
  port: 8001

#mybatis整合
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.li.pojo                  #所有pojo别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                #mapper映射文件

spring:
  profiles: dev
  application:
   name: cloud-config-dept-client    #注意这个名字很重要，就是对外暴露的微服务名字
  datasource:
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://192.168.31.147:3308/clouddb01?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
   type: com.alibaba.druid.pool.DruidDataSource
   dbcp2:
     min-idle: 5               #数据库连接池的最小维持连接数
     initial-size: 5          #初始化连接数
     max-total: 5             #最大连接数
     max-wait-millis: 200       #等待连接获取的最大超时时间


eureka:
  client:    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-dept-8001     #改eureka里面微服务连接的别名
    prefer-ip-address: true    #访问路径可以显示ip地址

#eureka点进连接后会显示的内容，注意主工程的pom要加东西
info:
  app.name: li-service-cloud
  company.name: www.yinweili.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  
 ----
 
 server:
  port: 8001

#mybatis整合
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.li.pojo                  #所有pojo别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                #mapper映射文件

spring:
  profiles: test
  application:
   name: cloud-config-dept-client    #注意这个名字很重要，就是对外暴露的微服务名字
  datasource:
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://192.168.31.147:3308/clouddb01?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
   type: com.alibaba.druid.pool.DruidDataSource
   dbcp2:
     min-idle: 5               #数据库连接池的最小维持连接数
     initial-size: 5          #初始化连接数
     max-total: 5             #最大连接数
     max-wait-millis: 200       #等待连接获取的最大超时时间


eureka:
  client:    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-dept-8001     #改eureka里面微服务连接的别名
    prefer-ip-address: true    #访问路径可以显示ip地址

#eureka点进连接后会显示的内容，注意主工程的pom要加东西
info:
  app.name: li-service-cloud
  company.name: www.yinweili.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$